music = {
    "chandramaniye" : "https://www.youtube.com/watch?v=SrygEX2Y8n0&pp=ygUNaGltY2hhbGkgc29uZw%3D%3D",
    "court side" : "https://www.youtube.com/watch?v=Z8IRRphKFZA&pp=ygUMa2FyYW4gYXVqbGEg",
    "at peace" : "https://www.youtube.com/watch?v=jVVwYXV22zg&pp=ygUMa2FyYW4gYXVqbGEg",
    "here and there": "https://www.youtube.com/watch?v=0g92o2bezkc",
    "yaar jatt de": "https://www.youtube.com/watch?v=9G62MZEh_1s",
    "chu gon do": "https://www.youtube.com/watch?v=ZjLU7eZZeQg",
    "ford": "https://www.youtube.com/watch?v=UMyWJX-snPM",
    "it arn't illeagle": "https://www.youtube.com/watch?v=e8a4YuRgGdU",
    "ask about me": "https://www.youtube.com/watch?v=k4AdBJQjeMI",
    "sharab": "https://www.youtube.com/watch?v=Rx4_knkQnbA",
    "its a hustle": "https://www.youtube.com/watch?v=X2cnLb1Qa0w",
    "feel the flava": "https://www.youtube.com/watch?v=A1wsIuSZu1U",
    "sheikh": "https://www.youtube.com/watch?v=4uMchksQJng",
    "batti bars": "https://www.youtube.com/watch?v=4DfVxVeqk2o",
    "winning speech": "https://www.youtube.com/watch?v=vsWxs1tuwDk",
    "on top": "https://www.youtube.com/watch?v=aFWDOFg7X2A",
    "admirin you": "https://www.youtube.com/watch?v=k85UB5b6pJU",
    "bachke bachke": "https://www.youtube.com/watch?v=fRJ03btNsao",
    "maxico": "https://www.youtube.com/watch?v=2sAzb3kraoQ",
    "players": "https://www.youtube.com/watch?v=CeFQO9MQNqs",
    "chithiyaan": "https://www.youtube.com/watch?v=M4DwGuTINsc",
    "pind nanke": "https://www.youtube.com/watch?v=oIgMjYZ6f_0",
    "adhiya": "https://www.youtube.com/watch?v=zsmcSN7sW0s",
    "goat": "https://www.youtube.com/watch?v=M8vDwlHigJA",
    "so high": "https://www.youtube.com/watch?v=GgmFC8y8q3k",
    "drippy": "https://www.youtube.com/watch?v=5ZKLM5pNoGQ",
    "lock": "https://www.youtube.com/watch?v=_wfrNbLguWw",
    "choosen": "https://www.youtube.com/watch?v=T6MFZH8k8tU",
    "devil": "https://www.youtube.com/watch?v=C4mBfkNVnEk",
    "mitra di chhatri": "https://www.youtube.com/watch?v=ioWkx6WRH2I",
    "pink pehra lagda": "https://www.youtube.com/watch?v=3C1dv9vzZnU",
    "touch wood": "https://www.youtube.com/watch?v=WFMVaigeOn4",
    "saun di jhadi": "https://www.youtube.com/watch?v=Iv7ls3mzPOU",
    "pakki kanak": "https://www.youtube.com/watch?v=1NoXtlEXWJg",
    "mehfil mitran di": "https://www.youtube.com/watch?v=0AJ0KuC8dCE",
    "dil tan pagal hai": "https://www.youtube.com/watch?v=mSs4Eh8ksM0",
    "kabaddi kabaddi": "https://www.youtube.com/watch?v=3jqGBie2-2c",
    "BA fail": "https://www.youtube.com/watch?v=iB_GYeEgd8c",
    "die with a smile": "https://www.youtube.com/watch?v=kPa7bsKwL-c",
    "bird of a feather": "https://www.youtube.com/watch?v=V9PVRfjEBTI",
    "sapphire": "https://www.youtube.com/watch?v=JgDNFQ2RaLQ",
    "dope shope": "https://youtu.be/NrXdauEv9HY",
    "brown rang": "https://youtu.be/eizmCZv3aKI",
    "haye mera dil": "https://youtu.be/I2uPSqNqrqU",
    "chaska": "https://youtu.be/gwoaVMIiwjo",
    "banda maarna": "https://youtu.be/BWgBR98-BBA",
    "high heels": "https://youtu.be/Tkgad9gngOQ",
    "char bottle vodka": "https://youtu.be/x8F5dz8kv1w",
    "bebo": "https://youtu.be/fB15QJmX7GM",
    "blue eyes": "https://youtu.be/NbyHNASFi6U",
    "call aundi": "https://youtu.be/OIv0FLrbnGE",
    "yaar bathere": "https://youtu.be/13uzQU0mfnM",
    "gabru": "https://youtu.be/q1wK0r51ARs",
    "party getting hot": "https://youtu.be/ZuoIW4aINak",
    "volume 1": "https://youtu.be/ovYPA6bhpF4",
    "london": "https://youtu.be/MhlecL-gx4s",
    "ohdi ankh bhi kamini": "https://youtu.be/tlKOtskkAlw",
    "angreji beat": "https://youtu.be/Iu8210k9WQc",
    "one bottle down": "https://youtu.be/TwFBtV13KQQ",
    "daftar ki girl": "https://youtu.be/rrOZa91iO2s",
    "goliyan": "https://youtu.be/WDOVxqsD3fs"
}